source "http://rubygems.org"
gem "thin"
gem "sinatra"
gem "quickbase_client"
gem "rack-flash"
gem "httpclient"
gem "gmail_sender"
gem "iron_worker"
gem "activesupport"
gem "i18n"
gem "right_aws"
gem "rack-ssl-enforcer"
gem "tzinfo"


